### ISSUE TITLE
iOS app

### ISSUE THREAD

**Issue by davepruitt** [CINPLA/nestify#205]
I can't seem to find the iOS app anywhere. When I attempt to browse to the link in my web browser, it just sits there and "thinks" and never seems to load the app's page. I've tried doing this from Italy as well as from the United States. Also, when I try to pull up the app's page on my iPhone, it tells me that the app is "not available in my region". Is the app still available for iOS? Is the app region-locked? This needs to be fixed.

**Comment by dragly** [comment]
I am afraid we will no longer have time to maintain the native versions of Neuronify, including the iOS version. However, there is a web version that hopefully should be useful: https://dragly.org/projects/neuronify/
